### ISSUE TITLE
import of landslide layers

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#619]
@pgiraud 
Do pre-processed landslide layers (prefix 'LS-') get harvested by the process currently? We have two layers in geonode that should be pulled into TH!

**Comment by pgiraud** [comment]
If I remember well, the "Landslide" hazard type was supposed to be added later. Thus we have never set the processing parameters for this hazard type.
See https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard_processing.yaml

Can you please tell what values we should use for the different levels?
ping @NicolasT-brgm

**Comment by stufraser1** [comment]
@NicolasT-brgm @pgiraud 
The raster values are already processed as Very Low, Low, Medium, and High (no value thresholds given). The unit in geonode metadata is Landslide Susceptibility Index.
It should be accepted the same way as volcano, if at all possible - I would very much appreciate if it can be included

**Comment by pgiraud** [comment]
I opened `sedac_ls_reclass.tiff` file in QGIS. Looks like there are 4 different values (from 0 to 4).
No_Data is supposed to be "value=15" but there's no pixel of that value.

Here's the value I set in the settings:
```
   LS:                     
    hazard_type: landslide
    values:               
     HIG: [4]            
     MED: [3]            
     LOW: [2]            
     VLO: [1]            
```

Is this correct?
